# Generated by Django 5.2.7 on 2025-11-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0011_alter_add_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
