# Generated by Django 5.2.7 on 2025-11-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0012_alter_add_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Textarea'), ('number', 'Number Input'), ('radio', 'Radio Options'), ('select', 'Dropdown Select'), ('multiselect', 'Multiselect'), ('slider', 'Slider'), ('checkbox', 'Checkbox'), ('file', 'File Upload')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('jobs', models.ManyToManyField(related_name='questions', to='create_job.add_job')),
            ],
        ),
    ]
