# Generated by Django 5.2.7 on 2025-11-26 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0014_country_state'),
        ('microsoft_teams', '0003_teamsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_hiring_manager', to='microsoft_teams.teamsuser'),
        ),
        migrations.AlterField(
            model_name='add_job',
            name='hr_team_members',
            field=models.ManyToManyField(related_name='jobs_as_hr', to='microsoft_teams.teamsuser'),
        ),
        migrations.AlterField(
            model_name='add_job',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_managed', to='microsoft_teams.teamsuser'),
        ),
        migrations.AlterField(
            model_name='add_job',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to='microsoft_teams.teamsuser'),
        ),
    ]
