# Generated by Django 5.2.7 on 2025-11-27 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0015_alter_add_job_hiring_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkillPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must', models.BooleanField(default=False)),
                ('good', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_preferences', to='create_job.add_job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_job.skills')),
            ],
        ),
    ]
