# Generated by Django 5.2.7 on 2025-11-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_teams', '0002_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_id', models.CharField(help_text="Microsoft Graph 'id'", max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=50, null=True)),
                ('user_principal_name', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('business_phones', models.JSONField(blank=True, help_text='Array of phone numbers', null=True)),
                ('raw_graph', models.JSONField(blank=True, help_text='Full original Graph JSON payload', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teams User',
                'verbose_name_plural': 'Teams Users',
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['user_principal_name'], name='microsoft_t_user_pr_3461c1_idx')],
            },
        ),
    ]
