# Generated by Django 5.2.7 on 2025-11-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_data', '0004_alter_formdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='cv_upload',
            field=models.FileField(default='', upload_to='cv_uploads/'),
        ),
    ]
